# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/djshaji/projects/opiqo-windows

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/djshaji/projects/opiqo-windows

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/djshaji/projects/opiqo-windows/CMakeFiles /home/djshaji/projects/opiqo-windows//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/djshaji/projects/opiqo-windows/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opiqo

# Build rule for target.
opiqo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opiqo
.PHONY : opiqo

# fast build rule for target.
opiqo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/build
.PHONY : opiqo/fast

#=============================================================================
# Target rules for targets named default

# Build rule for target.
default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 default
.PHONY : default

# fast build rule for target.
default/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/default.dir/build.make CMakeFiles/default.dir/build
.PHONY : default/fast

#=============================================================================
# Target rules for targets named zip

# Build rule for target.
zip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zip
.PHONY : zip

# fast build rule for target.
zip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zip.dir/build.make CMakeFiles/zip.dir/build
.PHONY : zip/fast

app.res: app.rc.res
.PHONY : app.res

# target to build an object file
app.rc.res:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/app.rc.res
.PHONY : app.rc.res

src/FileWriter.obj: src/FileWriter.cpp.obj
.PHONY : src/FileWriter.obj

# target to build an object file
src/FileWriter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/FileWriter.cpp.obj
.PHONY : src/FileWriter.cpp.obj

src/FileWriter.i: src/FileWriter.cpp.i
.PHONY : src/FileWriter.i

# target to preprocess a source file
src/FileWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/FileWriter.cpp.i
.PHONY : src/FileWriter.cpp.i

src/FileWriter.s: src/FileWriter.cpp.s
.PHONY : src/FileWriter.s

# target to generate assembly for a file
src/FileWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/FileWriter.cpp.s
.PHONY : src/FileWriter.cpp.s

src/LiveEffectEngine.obj: src/LiveEffectEngine.cpp.obj
.PHONY : src/LiveEffectEngine.obj

# target to build an object file
src/LiveEffectEngine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/LiveEffectEngine.cpp.obj
.PHONY : src/LiveEffectEngine.cpp.obj

src/LiveEffectEngine.i: src/LiveEffectEngine.cpp.i
.PHONY : src/LiveEffectEngine.i

# target to preprocess a source file
src/LiveEffectEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/LiveEffectEngine.cpp.i
.PHONY : src/LiveEffectEngine.cpp.i

src/LiveEffectEngine.s: src/LiveEffectEngine.cpp.s
.PHONY : src/LiveEffectEngine.s

# target to generate assembly for a file
src/LiveEffectEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/LiveEffectEngine.cpp.s
.PHONY : src/LiveEffectEngine.cpp.s

src/LockFreeQueue.obj: src/LockFreeQueue.cpp.obj
.PHONY : src/LockFreeQueue.obj

# target to build an object file
src/LockFreeQueue.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/LockFreeQueue.cpp.obj
.PHONY : src/LockFreeQueue.cpp.obj

src/LockFreeQueue.i: src/LockFreeQueue.cpp.i
.PHONY : src/LockFreeQueue.i

# target to preprocess a source file
src/LockFreeQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/LockFreeQueue.cpp.i
.PHONY : src/LockFreeQueue.cpp.i

src/LockFreeQueue.s: src/LockFreeQueue.cpp.s
.PHONY : src/LockFreeQueue.s

# target to generate assembly for a file
src/LockFreeQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/LockFreeQueue.cpp.s
.PHONY : src/LockFreeQueue.cpp.s

src/main_win32.obj: src/main_win32.cpp.obj
.PHONY : src/main_win32.obj

# target to build an object file
src/main_win32.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/main_win32.cpp.obj
.PHONY : src/main_win32.cpp.obj

src/main_win32.i: src/main_win32.cpp.i
.PHONY : src/main_win32.i

# target to preprocess a source file
src/main_win32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/main_win32.cpp.i
.PHONY : src/main_win32.cpp.i

src/main_win32.s: src/main_win32.cpp.s
.PHONY : src/main_win32.s

# target to generate assembly for a file
src/main_win32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/main_win32.cpp.s
.PHONY : src/main_win32.cpp.s

src/resample.obj: src/resample.c.obj
.PHONY : src/resample.obj

# target to build an object file
src/resample.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/resample.c.obj
.PHONY : src/resample.c.obj

src/resample.i: src/resample.c.i
.PHONY : src/resample.i

# target to preprocess a source file
src/resample.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/resample.c.i
.PHONY : src/resample.c.i

src/resample.s: src/resample.c.s
.PHONY : src/resample.s

# target to generate assembly for a file
src/resample.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/resample.c.s
.PHONY : src/resample.c.s

src/win32/AppSettings.obj: src/win32/AppSettings.cpp.obj
.PHONY : src/win32/AppSettings.obj

# target to build an object file
src/win32/AppSettings.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/AppSettings.cpp.obj
.PHONY : src/win32/AppSettings.cpp.obj

src/win32/AppSettings.i: src/win32/AppSettings.cpp.i
.PHONY : src/win32/AppSettings.i

# target to preprocess a source file
src/win32/AppSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/AppSettings.cpp.i
.PHONY : src/win32/AppSettings.cpp.i

src/win32/AppSettings.s: src/win32/AppSettings.cpp.s
.PHONY : src/win32/AppSettings.s

# target to generate assembly for a file
src/win32/AppSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/AppSettings.cpp.s
.PHONY : src/win32/AppSettings.cpp.s

src/win32/AudioEngine.obj: src/win32/AudioEngine.cpp.obj
.PHONY : src/win32/AudioEngine.obj

# target to build an object file
src/win32/AudioEngine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/AudioEngine.cpp.obj
.PHONY : src/win32/AudioEngine.cpp.obj

src/win32/AudioEngine.i: src/win32/AudioEngine.cpp.i
.PHONY : src/win32/AudioEngine.i

# target to preprocess a source file
src/win32/AudioEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/AudioEngine.cpp.i
.PHONY : src/win32/AudioEngine.cpp.i

src/win32/AudioEngine.s: src/win32/AudioEngine.cpp.s
.PHONY : src/win32/AudioEngine.s

# target to generate assembly for a file
src/win32/AudioEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/AudioEngine.cpp.s
.PHONY : src/win32/AudioEngine.cpp.s

src/win32/ControlBar.obj: src/win32/ControlBar.cpp.obj
.PHONY : src/win32/ControlBar.obj

# target to build an object file
src/win32/ControlBar.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/ControlBar.cpp.obj
.PHONY : src/win32/ControlBar.cpp.obj

src/win32/ControlBar.i: src/win32/ControlBar.cpp.i
.PHONY : src/win32/ControlBar.i

# target to preprocess a source file
src/win32/ControlBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/ControlBar.cpp.i
.PHONY : src/win32/ControlBar.cpp.i

src/win32/ControlBar.s: src/win32/ControlBar.cpp.s
.PHONY : src/win32/ControlBar.s

# target to generate assembly for a file
src/win32/ControlBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/ControlBar.cpp.s
.PHONY : src/win32/ControlBar.cpp.s

src/win32/MainWindow.obj: src/win32/MainWindow.cpp.obj
.PHONY : src/win32/MainWindow.obj

# target to build an object file
src/win32/MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/MainWindow.cpp.obj
.PHONY : src/win32/MainWindow.cpp.obj

src/win32/MainWindow.i: src/win32/MainWindow.cpp.i
.PHONY : src/win32/MainWindow.i

# target to preprocess a source file
src/win32/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/MainWindow.cpp.i
.PHONY : src/win32/MainWindow.cpp.i

src/win32/MainWindow.s: src/win32/MainWindow.cpp.s
.PHONY : src/win32/MainWindow.s

# target to generate assembly for a file
src/win32/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/MainWindow.cpp.s
.PHONY : src/win32/MainWindow.cpp.s

src/win32/ParameterPanel.obj: src/win32/ParameterPanel.cpp.obj
.PHONY : src/win32/ParameterPanel.obj

# target to build an object file
src/win32/ParameterPanel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/ParameterPanel.cpp.obj
.PHONY : src/win32/ParameterPanel.cpp.obj

src/win32/ParameterPanel.i: src/win32/ParameterPanel.cpp.i
.PHONY : src/win32/ParameterPanel.i

# target to preprocess a source file
src/win32/ParameterPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/ParameterPanel.cpp.i
.PHONY : src/win32/ParameterPanel.cpp.i

src/win32/ParameterPanel.s: src/win32/ParameterPanel.cpp.s
.PHONY : src/win32/ParameterPanel.s

# target to generate assembly for a file
src/win32/ParameterPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/ParameterPanel.cpp.s
.PHONY : src/win32/ParameterPanel.cpp.s

src/win32/PluginDialog.obj: src/win32/PluginDialog.cpp.obj
.PHONY : src/win32/PluginDialog.obj

# target to build an object file
src/win32/PluginDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/PluginDialog.cpp.obj
.PHONY : src/win32/PluginDialog.cpp.obj

src/win32/PluginDialog.i: src/win32/PluginDialog.cpp.i
.PHONY : src/win32/PluginDialog.i

# target to preprocess a source file
src/win32/PluginDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/PluginDialog.cpp.i
.PHONY : src/win32/PluginDialog.cpp.i

src/win32/PluginDialog.s: src/win32/PluginDialog.cpp.s
.PHONY : src/win32/PluginDialog.s

# target to generate assembly for a file
src/win32/PluginDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/PluginDialog.cpp.s
.PHONY : src/win32/PluginDialog.cpp.s

src/win32/PluginSlot.obj: src/win32/PluginSlot.cpp.obj
.PHONY : src/win32/PluginSlot.obj

# target to build an object file
src/win32/PluginSlot.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/PluginSlot.cpp.obj
.PHONY : src/win32/PluginSlot.cpp.obj

src/win32/PluginSlot.i: src/win32/PluginSlot.cpp.i
.PHONY : src/win32/PluginSlot.i

# target to preprocess a source file
src/win32/PluginSlot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/PluginSlot.cpp.i
.PHONY : src/win32/PluginSlot.cpp.i

src/win32/PluginSlot.s: src/win32/PluginSlot.cpp.s
.PHONY : src/win32/PluginSlot.s

# target to generate assembly for a file
src/win32/PluginSlot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/PluginSlot.cpp.s
.PHONY : src/win32/PluginSlot.cpp.s

src/win32/SettingsDialog.obj: src/win32/SettingsDialog.cpp.obj
.PHONY : src/win32/SettingsDialog.obj

# target to build an object file
src/win32/SettingsDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/SettingsDialog.cpp.obj
.PHONY : src/win32/SettingsDialog.cpp.obj

src/win32/SettingsDialog.i: src/win32/SettingsDialog.cpp.i
.PHONY : src/win32/SettingsDialog.i

# target to preprocess a source file
src/win32/SettingsDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/SettingsDialog.cpp.i
.PHONY : src/win32/SettingsDialog.cpp.i

src/win32/SettingsDialog.s: src/win32/SettingsDialog.cpp.s
.PHONY : src/win32/SettingsDialog.s

# target to generate assembly for a file
src/win32/SettingsDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/SettingsDialog.cpp.s
.PHONY : src/win32/SettingsDialog.cpp.s

src/win32/UpgradeDialog.obj: src/win32/UpgradeDialog.cpp.obj
.PHONY : src/win32/UpgradeDialog.obj

# target to build an object file
src/win32/UpgradeDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/UpgradeDialog.cpp.obj
.PHONY : src/win32/UpgradeDialog.cpp.obj

src/win32/UpgradeDialog.i: src/win32/UpgradeDialog.cpp.i
.PHONY : src/win32/UpgradeDialog.i

# target to preprocess a source file
src/win32/UpgradeDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/UpgradeDialog.cpp.i
.PHONY : src/win32/UpgradeDialog.cpp.i

src/win32/UpgradeDialog.s: src/win32/UpgradeDialog.cpp.s
.PHONY : src/win32/UpgradeDialog.s

# target to generate assembly for a file
src/win32/UpgradeDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/UpgradeDialog.cpp.s
.PHONY : src/win32/UpgradeDialog.cpp.s

src/win32/WasapiDeviceEnum.obj: src/win32/WasapiDeviceEnum.cpp.obj
.PHONY : src/win32/WasapiDeviceEnum.obj

# target to build an object file
src/win32/WasapiDeviceEnum.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/WasapiDeviceEnum.cpp.obj
.PHONY : src/win32/WasapiDeviceEnum.cpp.obj

src/win32/WasapiDeviceEnum.i: src/win32/WasapiDeviceEnum.cpp.i
.PHONY : src/win32/WasapiDeviceEnum.i

# target to preprocess a source file
src/win32/WasapiDeviceEnum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/WasapiDeviceEnum.cpp.i
.PHONY : src/win32/WasapiDeviceEnum.cpp.i

src/win32/WasapiDeviceEnum.s: src/win32/WasapiDeviceEnum.cpp.s
.PHONY : src/win32/WasapiDeviceEnum.s

# target to generate assembly for a file
src/win32/WasapiDeviceEnum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/WasapiDeviceEnum.cpp.s
.PHONY : src/win32/WasapiDeviceEnum.cpp.s

src/win32/win_logging.obj: src/win32/win_logging.cpp.obj
.PHONY : src/win32/win_logging.obj

# target to build an object file
src/win32/win_logging.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/win_logging.cpp.obj
.PHONY : src/win32/win_logging.cpp.obj

src/win32/win_logging.i: src/win32/win_logging.cpp.i
.PHONY : src/win32/win_logging.i

# target to preprocess a source file
src/win32/win_logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/win_logging.cpp.i
.PHONY : src/win32/win_logging.cpp.i

src/win32/win_logging.s: src/win32/win_logging.cpp.s
.PHONY : src/win32/win_logging.s

# target to generate assembly for a file
src/win32/win_logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opiqo.dir/build.make CMakeFiles/opiqo.dir/src/win32/win_logging.cpp.s
.PHONY : src/win32/win_logging.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... default"
	@echo "... zip"
	@echo "... opiqo"
	@echo "... app.res"
	@echo "... src/FileWriter.obj"
	@echo "... src/FileWriter.i"
	@echo "... src/FileWriter.s"
	@echo "... src/LiveEffectEngine.obj"
	@echo "... src/LiveEffectEngine.i"
	@echo "... src/LiveEffectEngine.s"
	@echo "... src/LockFreeQueue.obj"
	@echo "... src/LockFreeQueue.i"
	@echo "... src/LockFreeQueue.s"
	@echo "... src/main_win32.obj"
	@echo "... src/main_win32.i"
	@echo "... src/main_win32.s"
	@echo "... src/resample.obj"
	@echo "... src/resample.i"
	@echo "... src/resample.s"
	@echo "... src/win32/AppSettings.obj"
	@echo "... src/win32/AppSettings.i"
	@echo "... src/win32/AppSettings.s"
	@echo "... src/win32/AudioEngine.obj"
	@echo "... src/win32/AudioEngine.i"
	@echo "... src/win32/AudioEngine.s"
	@echo "... src/win32/ControlBar.obj"
	@echo "... src/win32/ControlBar.i"
	@echo "... src/win32/ControlBar.s"
	@echo "... src/win32/MainWindow.obj"
	@echo "... src/win32/MainWindow.i"
	@echo "... src/win32/MainWindow.s"
	@echo "... src/win32/ParameterPanel.obj"
	@echo "... src/win32/ParameterPanel.i"
	@echo "... src/win32/ParameterPanel.s"
	@echo "... src/win32/PluginDialog.obj"
	@echo "... src/win32/PluginDialog.i"
	@echo "... src/win32/PluginDialog.s"
	@echo "... src/win32/PluginSlot.obj"
	@echo "... src/win32/PluginSlot.i"
	@echo "... src/win32/PluginSlot.s"
	@echo "... src/win32/SettingsDialog.obj"
	@echo "... src/win32/SettingsDialog.i"
	@echo "... src/win32/SettingsDialog.s"
	@echo "... src/win32/UpgradeDialog.obj"
	@echo "... src/win32/UpgradeDialog.i"
	@echo "... src/win32/UpgradeDialog.s"
	@echo "... src/win32/WasapiDeviceEnum.obj"
	@echo "... src/win32/WasapiDeviceEnum.i"
	@echo "... src/win32/WasapiDeviceEnum.s"
	@echo "... src/win32/win_logging.obj"
	@echo "... src/win32/win_logging.i"
	@echo "... src/win32/win_logging.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

